use `system2` instead of system
eddelbuettel/inline pull request #12
Opened 2020-09-03 14:44 UTC by bgoodri

084dbdd is the the commit that actually changes to using the more portable `system2` rather than the older `system`, which fixes #11.  The rest of the commits were just me flailing around trying to get the error / verbosity reporting to be reasonable in more situations. You might have a different definition of reasonable, but I think the main two things were:

- Show what `make` would do by calling `R CMD SHLIB` with `--dry-run` if `verbose = TRUE` or if there was an error
- Show the end of the error message if it is too long to be printed in its entirety. R has an `option()` for this, but by default it is 10000 lines I think. Unfortunately, it is pretty common to have more than 10000 lines of unhelpful compiler warnings if using headers from BH or especially RcppEigen. So, if you feed the whole error file into `stop`, it would only show the first 10000 compiler warnings rather than the text of the actual compiler error. Now, it is feeding `tail(errmsg)` to `stop` when it exceeds the line limit, so you at least see the compiler error rather than the compiler warnings.

I ran `revdepcheck::revdep_check` under r-devel on Debian. mkin, RxODE, and themetagenomics have errors with inline on CRAN that are still errors with this PR but nothing got worse. I also ran it on Windows and didn't encounter any additional problems other than a couple packages were too complicated to install from source. Someone else ran it on Mac and said there were no additional problems. Other people have been installing my branch from GitHub and using it with RStan, so I think it is solid.

The `system2` function has an `env` argument that you might want to use to set the environmental variables rather than setting them in `cxxfunction`, but I didn't touch that.

2020-09-03 15:24 UTC, eddelbuettel requested changes

2020-09-03 15:24 UTC, eddelbuettel commented on DESCRIPTION
> +Date: 2020-07-11
Please revert that to (at the most) 0.3.15.1 and current date.

Setting releases is what Maintainer: does.

2020-09-03 15:25 UTC, eddelbuettel commented on DESCRIPTION
> +Date: 2020-07-11
Also rebasing/squashing may be a good idea though I can do that too when I merge.

2020-09-03 16:16 UTC, merged

2020-09-03 16:16 UTC, eddelbuettel commented
Thanks, squashed.  Having `system2()` is good.  It probably didn't exist yet when `inline` was written.

2020-09-06 15:52 UTC, eddelbuettel commented
Thanks again -- now on CRAN.

2020-09-06 15:57 UTC, bgoodri commented
Great!

On Sun, Sep 6, 2020 at 11:52 AM Dirk Eddelbuettel <notifications@github.com>
wrote:

> Thanks again -- now on CRAN.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eddelbuettel/inline/pull/12#issuecomment-687825683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZ2XKVBHSQSIMASECSFCODSEOV4NANCNFSM4QU3IHVQ>
> .
>